commitizen:
  name: cz_customize
  customize:
    message_template: "{{ticket_number}}: {{message}}"
    example: 'PL-0: this feature enable customize through config file'
    schema: "<ticket_number>: <body>"
    schema_pattern: "PL-[0-9]+:(\\s.*)"
    questions:
    - type: input
      name: ticket_number
      message: Ticket number -> PL-XXX
    - type: input
      name: message
      message: Body.
    - type: confirm
      name: show_message
      message: Do you want to add body message in commit?
